package FrontEnd;


/**
* FrontEnd/_FrontEndInterfaceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEnd.idl
* Friday, November 8, 2013 8:12:02 PM EST
*/

public class _FrontEndInterfaceStub extends org.omg.CORBA.portable.ObjectImpl implements FrontEnd.FrontEndInterface
{

  public String executeOperation (String method, String badgeId, String firstName, String lastName, String description, String status, String address, String lastDate, String lastLocation, String recordId, String remoteServerName)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("executeOperation", true);
                $out.write_string (method);
                $out.write_string (badgeId);
                $out.write_string (firstName);
                $out.write_string (lastName);
                $out.write_string (description);
                $out.write_string (status);
                $out.write_string (address);
                $out.write_string (lastDate);
                $out.write_string (lastLocation);
                $out.write_string (recordId);
                $out.write_string (remoteServerName);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return executeOperation (method, badgeId, firstName, lastName, description, status, address, lastDate, lastLocation, recordId, remoteServerName        );
            } finally {
                _releaseReply ($in);
            }
  } // executeOperation

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:FrontEnd/FrontEndInterface:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _FrontEndInterfaceStub
