package FrontEnd;


/**
* FrontEnd/FrontEndInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEnd.idl
* Friday, November 8, 2013 8:12:02 PM EST
*/

public interface FrontEndInterface extends FrontEndInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FrontEndInterface
