package FrontEnd;


/**
* FrontEnd/FrontEndInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEnd.idl
* Friday, November 8, 2013 8:12:02 PM EST
*/

public interface FrontEndInterfaceOperations 
{
  String executeOperation (String method, String badgeId, String firstName, String lastName, String description, String status, String address, String lastDate, String lastLocation, String recordId, String remoteServerName);
} // interface FrontEndInterfaceOperations
